language: java

services:
  - docker

jdk:
  - openjdk8
  - openjdk11

before_install:
  - chmod +x mvnw

install: true

cache:
  directories:
    - $HOME/.m2

script:
  - mvn -version
  - mvn -B -U -Possrh clean verify
