name: PR - Axon Server Connector Java

on:
  pull_request:

jobs:
  build:
    name: Test and Build on JDK ${{ matrix.java-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - java-version: 8
            sonar-enabled: false
          - java-version: 11
            sonar-enabled: false
          - java-version: 17
            sonar-enabled: true
          - java-version: 21
            sonar-enabled: true
      fail-fast: false # run both to the end

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
          cache: "maven"
          server-id: sonatype
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Build and Test with Sonar Analysis
        if: matrix.sonar-enabled
        run: |
          ./mvnw -B -U -Dstyle.color=always -Possrh -Pcoverage clean verify \
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=AxonIQ_axonserver-connector-java
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.CONNECTOR_SONAR_TOKEN }}

      - name: Build and Test without Sonar Analysis
        if: matrix.sonar-enabled != true
        run: |
          mvn -B -U -Dstyle.color=always -Possrh clean verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
