name: AxonServer Connector Java

on:
  pull_request:

jobs:
  build:
    name: Test and Build on JDK ${{ matrix.java-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - java-version: 8
            sonar-enabled: false
          - java-version: 11
            sonar-enabled: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3.2.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
          cache: "maven"
          server-id: sonatype
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Maven operation with Sonar
        if: matrix.sonar-enabled
        run: |
          mvn -B -U -Possrh -Pcoverage \
          clean verify \
          sonar:sonar \
          -Dsonar.projectKey=AxonIQ_axonserver-connector-java \
          -Dsonar.organization=axoniq \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Maven operation without Sonar
        if: matrix.sonar-enabled != true
        run: |
          mvn -B -U -Possrh clean verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
